### PR TITLE
remove dolmen.builtins dependency

### PR DESCRIPTION
**Pull request by papachoco**

### CODE REVIEW

**Comment by papachoco** [comment]
@jamadden remove dolmen.builtins dependency

**Comment by jamadden** [comment]
Can nti.base use the two interfaces defined here instead of defining its own? Things will get confusing otherwise...

That should work with the previous versions of this library too.

**Comment by papachoco** [comment]
we also use 
IDict  IList IString  INumeric IUnicode and  IIterable in other projects (e.g. nti.assesment) so they would have to be defined in nti.contentfragments

**Comment by jamadden** [comment]
> IDict IList IString INumeric IUnicode and IIterable in other projects (e.g. nti.assesment) so they would have to be defined in nti.contentfragments

I don't see why. Have nti.base import the interfaces defined here, have everything else import interfaces from nti.base.

**Comment by jamadden** [comment]
I'm going to make some tweaks to this and add an IBytes.

**Comment by papachoco** [comment]
I see .. once you have the changes I will update

**Review by jamadden — COMMENTED** [review]
LGTM. @papachoco how about you?

**Comment by papachoco** [comment]
Looks good as well..

**Comment by jamadden** [comment]
1.1.0 is on PyPI.

(If you have a PyPI username and want to be able to make releases, let me know. It's a matter of having zest.releaser[recommended] installed and running the 'fullrelease' command.)

**Pull request merged**
