### PR TITLE
Modify censored word list

### PR DESCRIPTION
**Pull request by ttarleton**

### CODE REVIEW

**Comment by cutz** [comment]
LGTM

**Comment by cutz** [comment]
@ttarleton looking at this more closely we also have a [whitelist](https://github.com/NextThought/nti.contentfragments/blob/master/src/nti/contentfragments/white_list.txt) that we could place this word in. That may be more appropriate in this case.

**Comment by cutz** [comment]
Whitelist isn't appropriate in this case as that whitelists full words not substrings. I think the change as you have it is fine. I need to look in to the travis failures and then we should be able to get a new build.

**Comment by cutz** [comment]
@jamadden i'm not sure what is going on with the travis checks here. tox passes cleanly locally for me

```bash
  pypy: commands succeeded
  py27: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  pypy3: commands succeeded
  py37: commands succeeded
  coverage: commands succeeded
  docs: commands succeeded
  congratulations :)
```

**Comment by jamadden** [comment]
Looks like we're hitting [this bug in PyPy 7.1](https://bitbucket.org/pypy/pypy/issues/3006/codecsdecode-failure-hex-decoder-returned). That was a regression from 7.0 that was fixed in 7.2 (travis is on 7.1, I assume you have something besides 7.1).

The quickest fix I see would be to put pypy3 in the [allowed failures configuration section](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail) for now.

**Pull request merged**
